// --- ADDED START: Multi-language support ---
const LANGS = {
  de: {name:"Deutsch",flag:"🇩🇪"},
  en: {name:"English",flag:"🇬🇧"},
  tr: {name:"Türkçe",flag:"🇹🇷"},
  fr: {name:"Français",flag:"🇫🇷"},
  es: {name:"Español",flag:"🇪🇸"},
  ar: {name:"العربية",flag:"🇸🇦",rtl:true},
};

const T = {
  de: {
    dashboard:"Dashboard",invoices:"Rechnungen",upload:"Upload",tableimport:"Tabelle Import",
    bookkeeping:"Kassenbuch",vault:"Belege",editor:"Beleg Editor",export:"Export",
    companies:"Firmen",pricing:"Preise",help:"Hilfe",feedback:"Feedback",chat:"AI Chat",
    logout:"Abmelden",save:"Speichern",cancel:"Abbrechen",delete:"Löschen",edit:"Bearbeiten",
    search:"Suchen",loading:"Laden...",vendor:"Lieferant",amount:"Betrag",date:"Datum",
    category:"Kategorie",vat:"MwSt",type:"Typ",expense:"Ausgabe",income:"Einnahme",
    total:"Gesamt",net:"Netto",gross:"Brutto",invoice_nr:"Rechnungs-Nr.",
    payment:"Zahlungsart",cash:"Bar",card:"Karte",transfer:"Überweisung",
    upload_title:"Rechnungen hochladen",upload_desc:"PDF, PNG, JPEG — bis zu 20 Dateien",
    upload_drop:"Dateien hierher ziehen",upload_click:"oder klicken",
    upload_photo:"Foto aufnehmen",upload_success:"erfolgreich hochgeladen",
    duplicate_title:"Rechnung bereits vorhanden",duplicate_msg:"Diese Rechnung wurde bereits hochgeladen.",
    duplicate_ask:"Erneut hochladen?",duplicate_yes:"Ja, erneut hochladen",
    duplicate_skip:"Duplikat — übersprungen",
    ocr_warn_empty:"OCR konnte den Text nicht lesen — bitte manuell prüfen",
    ocr_warn_amount:"Betrag nicht erkannt — bitte manuell eingeben",
    ocr_warn_vendor:"Lieferant nicht erkannt — bitte manuell eingeben",
    no_entries:"Keine Einträge",settings:"Einstellungen",language:"Sprache",
    food:"Lebensmittel",restaurant:"Restaurant",fuel:"Kraftstoff",transport:"Transport",
    office:"Büro",electronics:"Elektronik",clothing:"Kleidung",health:"Gesundheit",
    telecom:"Telekommunikation",insurance:"Versicherung",software:"Software",
    other:"Sonstige",reconciled:"Abgeglichen",not_reconciled:"Nicht abgeglichen",
    table_detect:"Tabelle erkennen",import_now:"Jetzt importieren",
    rows_detected:"Einträge erkannt",raw_text:"OCR Original",structured:"Strukturiert",
    save_to_book:"Jetzt ins Kassenbuch übernehmen",csv_save:"Als CSV speichern",
    new_file:"Neue Datei",how_it_works:"So funktioniert's",
    photo_label:"Bild / PDF",csv_label:"CSV",excel_label:"Excel",
    my_account:"Mein Konto",change_pw:"Passwort ändern",my_companies:"Meine Firmen",
    free_plan:"Free",early_plan:"Early Adopter",pro_plan:"Pro",
    original_show:"Original anzeigen",download:"Herunterladen",
    second_screen:"2. Bildschirm",load_original:"Original laden",
    finance_overview:"Übersicht deiner Finanzen",total_receipts:"Gesamt Belege",
    recognized:"Erkannte Belege",check:"Prüfen",monthly_trend:"Monatlicher Trend",
    by_category:"Nach Kategorie",recent:"Letzte Rechnungen",no_data:"Keine Daten",
    upload_files:"Dateien hierher ziehen",take_photo:"Foto aufnehmen",
    einvoice:"E-Rechnung (XML) importieren",entries:"Einträge",
    sync_invoices:"Rechnungen sync",new_entry:"+ Eintrag",reconcile:"Abgleichen",
    all_entries:"Alle Einträge",filter:"Filter",reset:"Zurücksetzen",
    confirm_delete:"Wirklich löschen?",deleted:"Gelöscht",saved:"Gespeichert",
    add_company:"Firma hinzufügen",save_company:"Firma speichern",remove:"Entfernen",
    no_company:"Noch keine Firma registriert",max_companies:"Maximum 2 Firmen erreicht",
    company_name:"Firmenname",address:"Adresse",phone_label:"Telefon",
    fax_label:"Fax",email_label:"E-Mail",website_label:"Webseite",
    tax_id_label:"USt-ID / Steuer-Nr.",iban_label:"IBAN",
    vat_rate:"MwSt-Satz",payment_method:"Zahlungsart",description:"Beschreibung",
    invoice_number:"Rechnungs-Nr.",processed:"Verarbeitet",not_processed:"Nicht verarbeitet",
  },
  en: {
    dashboard:"Dashboard",invoices:"Invoices",upload:"Upload",tableimport:"Table Import",
    bookkeeping:"Cash Book",vault:"Receipts",editor:"Receipt Editor",export:"Export",
    companies:"Companies",pricing:"Pricing",help:"Help",feedback:"Feedback",chat:"AI Chat",
    logout:"Sign Out",save:"Save",cancel:"Cancel",delete:"Delete",edit:"Edit",
    search:"Search",loading:"Loading...",vendor:"Vendor",amount:"Amount",date:"Date",
    category:"Category",vat:"VAT",type:"Type",expense:"Expense",income:"Income",
    total:"Total",net:"Net",gross:"Gross",invoice_nr:"Invoice No.",
    payment:"Payment Method",cash:"Cash",card:"Card",transfer:"Transfer",
    upload_title:"Upload Invoices",upload_desc:"PDF, PNG, JPEG — up to 20 files",
    upload_drop:"Drag files here",upload_click:"or click to select",
    upload_photo:"Take Photo",upload_success:"uploaded successfully",
    duplicate_title:"Invoice already exists",duplicate_msg:"This invoice was already uploaded.",
    duplicate_ask:"Upload again?",duplicate_yes:"Yes, upload again",
    duplicate_skip:"Duplicate — skipped",
    ocr_warn_empty:"OCR could not read the text — please check manually",
    ocr_warn_amount:"Amount not detected — please enter manually",
    ocr_warn_vendor:"Vendor not detected — please enter manually",
    no_entries:"No entries",settings:"Settings",language:"Language",
    food:"Food",restaurant:"Restaurant",fuel:"Fuel",transport:"Transport",
    office:"Office",electronics:"Electronics",clothing:"Clothing",health:"Health",
    telecom:"Telecom",insurance:"Insurance",software:"Software",
    other:"Other",reconciled:"Reconciled",not_reconciled:"Not reconciled",
    table_detect:"Detect Table",import_now:"Import Now",
    rows_detected:"entries detected",raw_text:"OCR Original",structured:"Structured",
    save_to_book:"Save to Cash Book",csv_save:"Save as CSV",
    new_file:"New File",how_it_works:"How it works",
    photo_label:"Image / PDF",csv_label:"CSV",excel_label:"Excel",
    my_account:"My Account",change_pw:"Change Password",my_companies:"My Companies",
    free_plan:"Free",early_plan:"Early Adopter",pro_plan:"Pro",
    original_show:"Show Original",download:"Download",
    second_screen:"2nd Screen",load_original:"Load Original",
    finance_overview:"Your financial overview",total_receipts:"Total Receipts",
    recognized:"Recognized Receipts",check:"Check",monthly_trend:"Monthly Trend",
    by_category:"By Category",recent:"Recent Invoices",no_data:"No data",
    upload_files:"Drag files here",take_photo:"Take Photo",
    einvoice:"Import E-Invoice (XML)",entries:"Entries",
    sync_invoices:"Sync Invoices",new_entry:"+ Entry",reconcile:"Reconcile",
    all_entries:"All Entries",filter:"Filter",reset:"Reset",
    confirm_delete:"Really delete?",deleted:"Deleted",saved:"Saved",
    add_company:"Add Company",save_company:"Save Company",remove:"Remove",
    no_company:"No company registered yet",max_companies:"Maximum 2 companies reached",
    company_name:"Company Name",address:"Address",phone_label:"Phone",
    fax_label:"Fax",email_label:"Email",website_label:"Website",
    tax_id_label:"Tax ID / VAT ID",iban_label:"IBAN",
    vat_rate:"VAT Rate",payment_method:"Payment Method",description:"Description",
    invoice_number:"Invoice No.",processed:"Processed",not_processed:"Not processed",
  },
  tr: {
    dashboard:"Panel",invoices:"Faturalar",upload:"Yükle",tableimport:"Tablo İçe Aktar",
    bookkeeping:"Kasa Defteri",vault:"Belgeler",editor:"Belge Düzenleyici",export:"Dışa Aktar",
    companies:"Firmalar",pricing:"Fiyatlar",help:"Yardım",feedback:"Geri Bildirim",chat:"AI Sohbet",
    logout:"Çıkış",save:"Kaydet",cancel:"İptal",delete:"Sil",edit:"Düzenle",
    search:"Ara",loading:"Yükleniyor...",vendor:"Firma",amount:"Tutar",date:"Tarih",
    category:"Kategori",vat:"KDV",type:"Tür",expense:"Gider",income:"Gelir",
    total:"Toplam",net:"Net",gross:"Brüt",invoice_nr:"Fatura No.",
    payment:"Ödeme Yöntemi",cash:"Nakit",card:"Kart",transfer:"Havale",
    upload_title:"Fatura Yükle",upload_desc:"PDF, PNG, JPEG — 20 dosyaya kadar",
    upload_drop:"Dosyaları buraya sürükle",upload_click:"veya tıklayın",
    upload_photo:"Fotoğraf Çek",upload_success:"başarıyla yüklendi",
    duplicate_title:"Fatura zaten mevcut",duplicate_msg:"Bu fatura daha önce yüklendi.",
    duplicate_ask:"Tekrar yüklensin mi?",duplicate_yes:"Evet, tekrar yükle",
    duplicate_skip:"Kopya — atlandı",
    ocr_warn_empty:"OCR metni okuyamadı — lütfen manuel kontrol edin",
    ocr_warn_amount:"Tutar algılanamadı — lütfen manuel girin",
    ocr_warn_vendor:"Firma algılanamadı — lütfen manuel girin",
    no_entries:"Kayıt yok",settings:"Ayarlar",language:"Dil",
    food:"Gıda",restaurant:"Restoran",fuel:"Yakıt",transport:"Ulaşım",
    office:"Ofis",electronics:"Elektronik",clothing:"Giyim",health:"Sağlık",
    telecom:"Telekom",insurance:"Sigorta",software:"Yazılım",
    other:"Diğer",reconciled:"Eşleştirildi",not_reconciled:"Eşleştirilmedi",
    table_detect:"Tablo Algıla",import_now:"Şimdi İçe Aktar",
    rows_detected:"kayıt algılandı",raw_text:"OCR Orijinal",structured:"Yapılandırılmış",
    save_to_book:"Kasa Defterine Kaydet",csv_save:"CSV olarak kaydet",
    new_file:"Yeni Dosya",how_it_works:"Nasıl çalışır",
    photo_label:"Fotoğraf / PDF",csv_label:"CSV",excel_label:"Excel",
    my_account:"Hesabım",change_pw:"Şifre Değiştir",my_companies:"Firmalarım",
    free_plan:"Ücretsiz",early_plan:"Erken Kullanıcı",pro_plan:"Pro",
    original_show:"Orijinali Göster",download:"İndir",
    second_screen:"2. Ekran",load_original:"Orijinal Yükle",
    finance_overview:"Finansal genel bakış",total_receipts:"Toplam Belge",
    recognized:"Tanınan Belgeler",check:"Kontrol",monthly_trend:"Aylık Trend",
    by_category:"Kategoriye Göre",recent:"Son Faturalar",no_data:"Veri yok",
    upload_files:"Dosyaları buraya sürükle",take_photo:"Fotoğraf Çek",
    einvoice:"E-Fatura (XML) İçe Aktar",entries:"Kayıtlar",
    sync_invoices:"Faturaları Senkronize Et",new_entry:"+ Kayıt",reconcile:"Eşleştir",
    all_entries:"Tüm Kayıtlar",filter:"Filtre",reset:"Sıfırla",
    confirm_delete:"Silmek istediğinize emin misiniz?",deleted:"Silindi",saved:"Kaydedildi",
    add_company:"Firma Ekle",save_company:"Firmayı Kaydet",remove:"Kaldır",
    no_company:"Henüz firma kaydedilmedi",max_companies:"Maksimum 2 firma (Beta)",
    company_name:"Firma Adı",address:"Adres",phone_label:"Telefon",
    fax_label:"Faks",email_label:"E-Posta",website_label:"Web Sitesi",
    tax_id_label:"Vergi No.",iban_label:"IBAN",
    vat_rate:"KDV Oranı",payment_method:"Ödeme Yöntemi",description:"Açıklama",
    invoice_number:"Fatura No.",processed:"İşlendi",not_processed:"İşlenmedi",
  },
  fr: {
    dashboard:"Tableau de bord",invoices:"Factures",upload:"Télécharger",tableimport:"Import Tableau",
    bookkeeping:"Livre de caisse",vault:"Reçus",editor:"Éditeur de reçus",export:"Exporter",
    companies:"Entreprises",pricing:"Tarifs",help:"Aide",feedback:"Retour",chat:"Chat IA",
    logout:"Déconnexion",save:"Enregistrer",cancel:"Annuler",delete:"Supprimer",edit:"Modifier",
    search:"Rechercher",loading:"Chargement...",vendor:"Fournisseur",amount:"Montant",date:"Date",
    category:"Catégorie",vat:"TVA",type:"Type",expense:"Dépense",income:"Revenu",
    total:"Total",net:"Net",gross:"Brut",invoice_nr:"N° facture",
    payment:"Mode de paiement",cash:"Espèces",card:"Carte",transfer:"Virement",
    upload_title:"Télécharger des factures",upload_desc:"PDF, PNG, JPEG — jusqu'à 20 fichiers",
    upload_drop:"Glissez les fichiers ici",upload_click:"ou cliquez",
    upload_photo:"Prendre une photo",upload_success:"téléchargé avec succès",
    duplicate_title:"Facture déjà existante",duplicate_msg:"Cette facture a déjà été téléchargée.",
    duplicate_ask:"Télécharger à nouveau?",duplicate_yes:"Oui, télécharger à nouveau",
    duplicate_skip:"Doublon — ignoré",
    ocr_warn_empty:"L'OCR n'a pas pu lire le texte — vérifiez manuellement",
    ocr_warn_amount:"Montant non détecté — saisissez manuellement",
    ocr_warn_vendor:"Fournisseur non détecté — saisissez manuellement",
    no_entries:"Aucune entrée",settings:"Paramètres",language:"Langue",
    food:"Alimentation",restaurant:"Restaurant",fuel:"Carburant",transport:"Transport",
    office:"Bureau",electronics:"Électronique",clothing:"Vêtements",health:"Santé",
    telecom:"Télécom",insurance:"Assurance",software:"Logiciel",
    other:"Autre",reconciled:"Rapproché",not_reconciled:"Non rapproché",
    table_detect:"Détecter le tableau",import_now:"Importer maintenant",
    rows_detected:"entrées détectées",raw_text:"OCR Original",structured:"Structuré",
    save_to_book:"Enregistrer dans le livre de caisse",csv_save:"Enregistrer en CSV",
    new_file:"Nouveau fichier",how_it_works:"Comment ça marche",
    photo_label:"Image / PDF",csv_label:"CSV",excel_label:"Excel",
    my_account:"Mon compte",change_pw:"Changer le mot de passe",my_companies:"Mes entreprises",
    free_plan:"Gratuit",early_plan:"Early Adopter",pro_plan:"Pro",
    original_show:"Voir l'original",download:"Télécharger",
    second_screen:"2ème écran",load_original:"Charger l'original",
    finance_overview:"Aperçu financier",total_receipts:"Total Reçus",
    recognized:"Reçus reconnus",check:"Vérifier",monthly_trend:"Tendance mensuelle",
    by_category:"Par catégorie",recent:"Dernières factures",no_data:"Aucune donnée",
    upload_files:"Glissez les fichiers ici",take_photo:"Prendre une photo",
    einvoice:"Importer E-Facture (XML)",entries:"Entrées",
    sync_invoices:"Synchroniser factures",new_entry:"+ Entrée",reconcile:"Rapprocher",
    all_entries:"Toutes les entrées",filter:"Filtrer",reset:"Réinitialiser",
    confirm_delete:"Vraiment supprimer?",deleted:"Supprimé",saved:"Enregistré",
    add_company:"Ajouter entreprise",save_company:"Enregistrer",remove:"Supprimer",
    no_company:"Aucune entreprise enregistrée",max_companies:"Maximum 2 entreprises",
    company_name:"Nom de l'entreprise",address:"Adresse",phone_label:"Téléphone",
    fax_label:"Fax",email_label:"E-mail",website_label:"Site web",
    tax_id_label:"N° TVA",iban_label:"IBAN",
    vat_rate:"Taux TVA",payment_method:"Mode de paiement",description:"Description",
    invoice_number:"N° facture",processed:"Traité",not_processed:"Non traité",
  },
  es: {
    dashboard:"Panel",invoices:"Facturas",upload:"Subir",tableimport:"Importar Tabla",
    bookkeeping:"Libro de caja",vault:"Recibos",editor:"Editor de recibos",export:"Exportar",
    companies:"Empresas",pricing:"Precios",help:"Ayuda",feedback:"Comentarios",chat:"Chat IA",
    logout:"Cerrar sesión",save:"Guardar",cancel:"Cancelar",delete:"Eliminar",edit:"Editar",
    search:"Buscar",loading:"Cargando...",vendor:"Proveedor",amount:"Importe",date:"Fecha",
    category:"Categoría",vat:"IVA",type:"Tipo",expense:"Gasto",income:"Ingreso",
    total:"Total",net:"Neto",gross:"Bruto",invoice_nr:"N° factura",
    payment:"Método de pago",cash:"Efectivo",card:"Tarjeta",transfer:"Transferencia",
    upload_title:"Subir facturas",upload_desc:"PDF, PNG, JPEG — hasta 20 archivos",
    upload_drop:"Arrastra los archivos aquí",upload_click:"o haz clic",
    upload_photo:"Tomar foto",upload_success:"subido correctamente",
    duplicate_title:"Factura ya existente",duplicate_msg:"Esta factura ya fue subida.",
    duplicate_ask:"¿Subir de nuevo?",duplicate_yes:"Sí, subir de nuevo",
    duplicate_skip:"Duplicado — omitido",
    ocr_warn_empty:"OCR no pudo leer el texto — revise manualmente",
    ocr_warn_amount:"Importe no detectado — ingrese manualmente",
    ocr_warn_vendor:"Proveedor no detectado — ingrese manualmente",
    no_entries:"Sin entradas",settings:"Configuración",language:"Idioma",
    food:"Alimentos",restaurant:"Restaurante",fuel:"Combustible",transport:"Transporte",
    office:"Oficina",electronics:"Electrónica",clothing:"Ropa",health:"Salud",
    telecom:"Telecom",insurance:"Seguro",software:"Software",
    other:"Otro",reconciled:"Conciliado",not_reconciled:"No conciliado",
    table_detect:"Detectar tabla",import_now:"Importar ahora",
    rows_detected:"entradas detectadas",raw_text:"OCR Original",structured:"Estructurado",
    save_to_book:"Guardar en libro de caja",csv_save:"Guardar como CSV",
    new_file:"Nuevo archivo",how_it_works:"Cómo funciona",
    photo_label:"Imagen / PDF",csv_label:"CSV",excel_label:"Excel",
    my_account:"Mi cuenta",change_pw:"Cambiar contraseña",my_companies:"Mis empresas",
    free_plan:"Gratis",early_plan:"Early Adopter",pro_plan:"Pro",
    original_show:"Ver original",download:"Descargar",
    second_screen:"2ª pantalla",load_original:"Cargar original",
    finance_overview:"Resumen financiero",total_receipts:"Total Recibos",
    recognized:"Recibos reconocidos",check:"Verificar",monthly_trend:"Tendencia mensual",
    by_category:"Por categoría",recent:"Últimas facturas",no_data:"Sin datos",
    upload_files:"Arrastra los archivos aquí",take_photo:"Tomar foto",
    einvoice:"Importar E-Factura (XML)",entries:"Entradas",
    sync_invoices:"Sincronizar facturas",new_entry:"+ Entrada",reconcile:"Conciliar",
    all_entries:"Todas las entradas",filter:"Filtrar",reset:"Reiniciar",
    confirm_delete:"¿Eliminar?",deleted:"Eliminado",saved:"Guardado",
    add_company:"Agregar empresa",save_company:"Guardar",remove:"Eliminar",
    no_company:"Sin empresas registradas",max_companies:"Máximo 2 empresas",
    company_name:"Nombre empresa",address:"Dirección",phone_label:"Teléfono",
    fax_label:"Fax",email_label:"Correo",website_label:"Sitio web",
    tax_id_label:"NIF / CIF",iban_label:"IBAN",
    vat_rate:"Tipo IVA",payment_method:"Método de pago",description:"Descripción",
    invoice_number:"N° factura",processed:"Procesado",not_processed:"No procesado",
  },
  ar: {
    dashboard:"لوحة التحكم",invoices:"الفواتير",upload:"رفع",tableimport:"استيراد جدول",
    bookkeeping:"دفتر النقد",vault:"الإيصالات",editor:"محرر الإيصالات",export:"تصدير",
    companies:"الشركات",pricing:"الأسعار",help:"مساعدة",feedback:"ملاحظات",chat:"دردشة AI",
    logout:"تسجيل خروج",save:"حفظ",cancel:"إلغاء",delete:"حذف",edit:"تعديل",
    search:"بحث",loading:"جاري التحميل...",vendor:"المورد",amount:"المبلغ",date:"التاريخ",
    category:"الفئة",vat:"ضريبة",type:"النوع",expense:"مصروف",income:"إيراد",
    total:"الإجمالي",net:"صافي",gross:"إجمالي",invoice_nr:"رقم الفاتورة",
    payment:"طريقة الدفع",cash:"نقداً",card:"بطاقة",transfer:"تحويل",
    upload_title:"رفع الفواتير",upload_desc:"PDF, PNG, JPEG — حتى 20 ملف",
    upload_drop:"اسحب الملفات هنا",upload_click:"أو انقر للاختيار",
    upload_photo:"التقاط صورة",upload_success:"تم الرفع بنجاح",
    duplicate_title:"الفاتورة موجودة",duplicate_msg:"تم رفع هذه الفاتورة مسبقاً",
    duplicate_ask:"رفع مرة أخرى؟",duplicate_yes:"نعم، ارفع مرة أخرى",
    duplicate_skip:"مكرر — تم التخطي",
    ocr_warn_empty:"تعذر قراءة النص — يرجى المراجعة يدوياً",
    ocr_warn_amount:"لم يتم اكتشاف المبلغ — أدخله يدوياً",
    ocr_warn_vendor:"لم يتم اكتشاف المورد — أدخله يدوياً",
    no_entries:"لا توجد إدخالات",settings:"الإعدادات",language:"اللغة",
    food:"طعام",restaurant:"مطعم",fuel:"وقود",transport:"نقل",
    office:"مكتب",electronics:"إلكترونيات",clothing:"ملابس",health:"صحة",
    telecom:"اتصالات",insurance:"تأمين",software:"برمجيات",
    other:"أخرى",reconciled:"مطابق",not_reconciled:"غير مطابق",
    table_detect:"كشف الجدول",import_now:"استيراد الآن",
    rows_detected:"إدخالات مكتشفة",raw_text:"النص الأصلي",structured:"منظم",
    save_to_book:"حفظ في دفتر النقد",csv_save:"حفظ كـ CSV",
    new_file:"ملف جديد",how_it_works:"كيف يعمل",
    photo_label:"صورة / PDF",csv_label:"CSV",excel_label:"Excel",
    my_account:"حسابي",change_pw:"تغيير كلمة المرور",my_companies:"شركاتي",
    free_plan:"مجاني",early_plan:"مبكر",pro_plan:"احترافي",
    original_show:"عرض الأصل",download:"تنزيل",
    second_screen:"شاشة ثانية",load_original:"تحميل الأصل",
    finance_overview:"نظرة مالية عامة",total_receipts:"إجمالي الإيصالات",
    recognized:"إيصالات معترف بها",check:"تحقق",monthly_trend:"الاتجاه الشهري",
    by_category:"حسب الفئة",recent:"آخر الفواتير",no_data:"لا توجد بيانات",
    upload_files:"اسحب الملفات هنا",take_photo:"التقاط صورة",
    einvoice:"استيراد فاتورة إلكترونية",entries:"الإدخالات",
    sync_invoices:"مزامنة الفواتير",new_entry:"+ إدخال",reconcile:"مطابقة",
    all_entries:"جميع الإدخالات",filter:"تصفية",reset:"إعادة تعيين",
    confirm_delete:"حذف بالتأكيد؟",deleted:"تم الحذف",saved:"تم الحفظ",
    add_company:"إضافة شركة",save_company:"حفظ",remove:"إزالة",
    no_company:"لم يتم تسجيل شركة",max_companies:"الحد الأقصى شركتان",
    company_name:"اسم الشركة",address:"العنوان",phone_label:"الهاتف",
    fax_label:"فاكس",email_label:"البريد",website_label:"الموقع",
    tax_id_label:"الرقم الضريبي",iban_label:"IBAN",
    vat_rate:"نسبة الضريبة",payment_method:"طريقة الدفع",description:"الوصف",
    invoice_number:"رقم الفاتورة",processed:"تمت المعالجة",not_processed:"لم تتم المعالجة",
  },
};

// Get/set language
function getLang() { return localStorage.getItem("atx_lang") || navigator.language?.substring(0,2) || "de"; }
function setLang(code) { localStorage.setItem("atx_lang", code); window.location.reload(); }
function t(key) { var lang = getLang(); return (T[lang] && T[lang][key]) || (T.de && T.de[key]) || key; }
// --- ADDED END ---
